# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'PDFNet', podspec: 'https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec'

end
